Create facebook-user-login
#Facebook login using the Parse SDK 
requires that the Facebook SDK already be loaded before calling Parse.FacebookUtils.init().

When this code is run, the following happens:

    The user is shown the Facebook login dialog.
    The user authenticates via Facebook, and your app receives a callback.
    Our SDK receives the Facebook data and saves it to a Parse.User. If it's a new user based on the Facebook ID, then that user is created.
    Your success callback is called with the user.

You may optionally provide a comma-delimited string that specifies what permissions your app requires from the Facebook user. For example:
Parse.FacebookUtils.logIn("user_likes,email", {
  success: function(user) {
    // Handle successful login
  },
  error: function(user, error) {
    // Handle errors and cancellation
  }
});